export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_LOADING = "USER_REGISTER_LOADING";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const ALL_FOODS_DETAILS_LOADING = "ALL_FOODS_DETAILS_LOADING";
export const ALL_FOODS_DETAILS_FAILED = "ALL_FOODS_DETAILS_FAILED";
export const ALL_FOODS_DETAILS_SUCESS = "ALL_FOODS_DETAILS_SUCESS";

export const GET_FOODS_DETAILS_LOADING = "GET_FOODS_DETAILS_LOADING";
export const GET_FOODS_DETAILS_FAILED = "GET_FOODS_DETAILS_FAILED";
export const GET_FOODS_DETAILS_SUCESS = "GET_FOODS_DETAILS_SUCESS";

export const ADD_FOODS_LOADING = "ADD_FOODS_LOADING";
export const ADD_FOODS_FAILED = "ADD_FOODS_FAILED";
export const ADD_FOODS_SUCESS = "ADD_FOODS_SUCESS";

export const UPDATE_FOOD_DETAILS_LOADING = "UPDATE_FOOD_DETAILS_LOADING";
export const UPDATE_FOOD_DETAILS_FAILED = "UPDATE_FOOD_DETAILS_FAILED";
export const UPDATE_FOOD_DETAILS_SUCESS = "UPDATE_FOOD_DETAILS_SUCESS";

export const DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS";
export const DELETE_FOOD_UPDATE = "DELETE_FOOD_UPDATE";
export const DELETE_FOOD_FAIL = "DELETE_FOOD_FAIL";

export const CLEAR_DATA = "CLEAR_DATA";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
export const LOAD_USER_LOADING = "LOAD_USER_LOADING";

export const DLETED_USER_SUCCESS = "DLETED_USER_SUCCESS";
export const DLETED_USER_FAIL = "DLETED_USER_FAIL";
export const DLETED_USER_LOAING = "DLETED_USER_LOAING";

export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";
export const GET_ALL_USER_LOADING = "GET_ALL_USER_LOADING";

export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAIL = "GET_USER_BY_ID_FAIL";
export const GET_USER_BY_ID_LOADING = "GET_USER_BY_ID_LOADING";

export const GET_FOODS_BY_USERID_LOADING = "GET_FOODS_BY_USERID_LOADING";
export const GET_FOODS_BY_USERID_SUCCESS = "GET_FOODS_BY_USERID_SUCCESS";
export const GET_FOODS_BY_USERID_ERROR = "GET_FOODS_BY_USERID_ERROR";

export const SEND_FRIENDS_LOADING = "SEND_FRIENDS_LOADING";
export const SEND_FRIENDS_SUCCESS = "SEND_FRIENDS_SUCCESS";
export const SEND_FRIENDS_FAIL = "SEND_FRIENDS_FAIL";

export const SHOW_WARNING = "SHOW_WARNING";
export const CLEAR_WARNING = "CLEAR_WARNING";
